version: '2'
services:
    testmap-app:
        image: testmap
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testmap-postgresql:5432/testmap
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testmap-postgresql:
        extends:
            file: postgresql.yml
            service: testmap-postgresql
